tap "homebrew/bundle"
tap "minio/stable"
brew "curl"
brew "fastfetch"
brew "git-delta"
brew "hcloud"
brew "helix"
brew "hugo"
brew "lazygit"
brew "mpv"
brew "neovim"
brew "zellij"
brew "zig"
brew "minio/stable/minio"
brew "chezmoi"
brew install chezmoi
